# Spring Properties
spring:
  application:
    name: player-service

server:
  port: 2222

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
  instance:
    leaseRenewalIntervalInSeconds: 5 #<-- DO NOT do this in prod.