# Configure this as the Service Discovery Server
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false

server:
  port: 1111

# Discovery Server Dashboard uses FreeMarker. Do not want the Thymeleaf template engine.
spring:
  thymeleaf:
    enabled: false #Disable Thymeleaf