# Spring Properties
spring:
  application:
    name: web-player-server

server:
  port: 3333

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.150:1111/eureka
  instance:
    leaseRenewalIntervalInSeconds: 5 #<-- DO NOT do this in prod.