# Spring properties
spring:
  application:
    name: web-player-server

# HTTP server
server:
  port: 3333

# Service Discovery (Eureka)
eureka:
  instance:
    leaseRenewalIntervalSeconds: 5 # DO NOT DO THIS IN PROD
  client:
    serviceUrl:
      defaultZone: http://192.168.0.150:1111/eureka