-- CRYPTO_COIN
drop table T_CRYPTO_COIN if exists;
create table T_CRYPTO_COIN (id bigint generated by default as identity (START WITH 1, INCREMENT BY 1) NOT NULL primary key,
                        coin_name varchar(64) not null,
                        coin_value float not null,
                        coin_outstanding float not null);

ALTER TABLE T_CRYPTO_COIN ALTER COLUMN coin_value SET DEFAULT 0;
ALTER TABLE T_CRYPTO_COIN ALTER COLUMN coin_outstanding SET DEFAULT 0;



-- PRICE_HISTORY
drop table T_PRICE_HISTORY if exists;
create table T_PRICE_HISTORY (id bigint generated by default as identity (START WITH 1, INCREMENT BY 1) NOT NULL primary key,
                        crypto_coin_id bigint not null,
                        history_time timestamp not null,
                        historic_price float not null);

ALTER TABLE T_PRICE_HISTORY ALTER COLUMN history_time SET DEFAULT CURRENT_TIMESTAMP;


-- TRANSACTION
drop table T_TRANSACTION if exists;
create table T_TRANSACTION (id bigint generated by default as identity (START WITH 1, INCREMENT BY 1) NOT NULL primary key,
                        receiving_player_id bigint not null,
                        sending_player_id bigint not null,
                        sent_crypto_coin_id bigint not null,
                        crypto_coin_amount float not null,
                        crypto_coin_value float not null,
                        received_crypto_coin_id bigint not null);